name: Java CI

on:
    push:
    pull_request:
        branches:
            - '*'

jobs:
    Build:
        strategy:
            matrix:
                jdkversion: [ 21 ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.jdkversion }}
                  cache: 'maven'
            - name: Build
              run: mvn -V -B clean package --file pom.xml
            - name: Upload Citizens Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Citizens-Colorful
                  path: ./dist/target/Citizens-*.jar
